#ifndef _MODEL_h_
#define _MODEL_h_

#define Faroe

enum Scan_RET
{
    RETSCAN_OK = 0,
    RETSCAN_ERRORDLL = 1,
    RETSCAN_OPENFAIL = 2,
    RETSCAN_ERRORPARAMETER = 3,
    RETSCAN_NO_ENOUGH_SPACE = 5,
    RETSCAN_ERROR_PORT = 6,
    RETSCAN_CANCEL = 7,
    RETSCAN_BUSY = 8,
    RETSCAN_ERROR = 9,
    RETSCAN_OPENFAIL_NET = 10,
    RETSCAN_PAPER_JAM = 11,
    RETSCAN_COVER_OPEN = 12,
    RETSCAN_PAPER_NOT_READY = 13,
    RETSCAN_CREATE_JOB_FAIL = 14,
    RETSCAN_ADFCOVER_NOT_READY = 15,
    RETSCAN_HOME_NOT_READY = 16,
    RETSCAN_ULTRA_SONIC = 17,
    RETSCAN_ERROR_POWER1 = 18,
    RETSCAN_ERROR_POWER2 = 19,
    RETSCAN_JOB_MISSING = 20,
    RETSCAN_JOB_GOGING = 21,
    RETSCAN_TIME_OUT = 22,
    RETSCAN_USB_TRANSFERERROR = 23,
    RETSCAN_WIFI_TRANSFERERROR = 24,
    RETSCAN_ADFPATH_NOT_READY = 25,
    RETSCAN_ADFDOC_NOT_READY = 26,
    RETSCAN_GETINFO_FAIL = 27,
};


#endif//_MODEL_h_

